
---


- name: filebeat config
  hosts: web, joomla, sql

  tasks:

  - name: copy filebeat config
    ansible.builtin.copy:
     src: /git/cprd-inf-log01/filebeat.yml
     dest: /etc/filebeat/filebeat.yml
     mode: '0600'


  - name: add filebeat service to auto
    ansible.builtin.shell: systemctl enable --now filebeat.service


  - name: Restart filebeat
    ansible.builtin.systemd_service:
     name: filebeat
     state: restarted
