

---
- name: grafana config
  hosts: cprd-inf-graf01

  tasks:



  - name: stop grafana
    ansible.builtin.systemd_service:
     name: grafana-server
     state: stopped


  - name: copy grafana ini
    ansible.builtin.copy:
     src: /git/cprd-inf-graf01/grafana.ini
     dest: /etc/grafana/grafana.ini
     mode: '0640'
     owner: grafana
     group: grafana



  - name: copy grafana db
    ansible.builtin.copy:
     src: /git/cprd-inf-graf01/grafana.db
     dest: /var/lib/grafana/grafana.db
     mode: '0640'
     owner: grafana
     group: grafana

  - name: Restart grafana
    ansible.builtin.systemd_service:
     name: grafana-server
     state: restarted
