---


- name: prometheus config with hosts
  hosts: cprd-inf-prom01

  tasks:



  - name: copy prometheus config
    ansible.builtin.copy:
     src: /git/cprd-inf-prom01/prometheus.yml
     dest: /etc/prometheus/prometheus.yml

  - name: copy ssl config
    ansible.builtin.copy:
     src: /git/cprd-inf-prom01/web.yml
     dest: /etc/prometheus/web.yml


  - name: Restart prometheus
    ansible.builtin.systemd_service:
     name: prometheus
     state: restarted
